-- MySQL Script generated by MySQL Workbench
-- sáb 18 jun 2016 14:45:29 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ETLMIO
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ETLMIO` ;

-- -----------------------------------------------------
-- Schema ETLMIO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ETLMIO` DEFAULT CHARACTER SET utf8 ;
USE `ETLMIO` ;

-- -----------------------------------------------------
-- Table `ETLMIO`.`dim_fecha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ETLMIO`.`dim_fecha` ;

CREATE TABLE IF NOT EXISTS `ETLMIO`.`dim_fecha` (
  `id_fecha` INT NOT NULL AUTO_INCREMENT,
  `fecha_bruta` VARCHAR(45) NOT NULL,
  `fecha_limpia` VARCHAR(45) NOT NULL,
  `anio` INT NOT NULL,
  `mes` INT NOT NULL,
  `nombre_mes` VARCHAR(45) NOT NULL,
  `semana_anio` INT NOT NULL,
  `semana_mes` INT NOT NULL,
  `dia_anio` INT NOT NULL,
  `dia` INT NOT NULL,
  `dia_semana_mes` INT NOT NULL,
  `nombre_dia` VARCHAR(45) NOT NULL,
  `numero_dia_semana` INT NOT NULL,
  `es_festivo` TINYINT(1) NOT NULL,
  `nombre_festivo` VARCHAR(45) NOT NULL,
  `es_feriado` TINYINT(1) NOT NULL,
  `nombre_feriado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_fecha`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla que almacena la Dimension Fecha';


-- -----------------------------------------------------
-- Table `ETLMIO`.`dim_tiempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ETLMIO`.`dim_tiempo` ;

CREATE TABLE IF NOT EXISTS `ETLMIO`.`dim_tiempo` (
  `id_tiempo` INT NOT NULL AUTO_INCREMENT,
  `tiempo_bruto` VARCHAR(45) NOT NULL,
  `hora_inicio` INT NOT NULL,
  `hora_fin` INT NOT NULL,
  PRIMARY KEY (`id_tiempo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla que almacena la Dimension Tiempo';


-- -----------------------------------------------------
-- Table `ETLMIO`.`dim_ruta_estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ETLMIO`.`dim_ruta_estacion` ;

CREATE TABLE IF NOT EXISTS `ETLMIO`.`dim_ruta_estacion` (
  `id_ruta_estacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_ruta_estacion` VARCHAR(45) NOT NULL,
  `es_ruta` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_ruta_estacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla que almacena la Dimension Ruta-Estacion';


-- -----------------------------------------------------
-- Table `ETLMIO`.`frecuencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ETLMIO`.`frecuencias` ;

CREATE TABLE IF NOT EXISTS `ETLMIO`.`frecuencias` (
  `id_frecuencia` INT NOT NULL AUTO_INCREMENT,
  `fk_fecha` INT NOT NULL,
  `fk_tiempo` INT NOT NULL,
  `fk_ruta_estacion` INT NOT NULL,
  `cant_pasajeros` INT NOT NULL,
  PRIMARY KEY (`id_frecuencia`, `fk_fecha`, `fk_tiempo`, `fk_ruta_estacion`),
  INDEX `fk_frecuencias_dim_fecha_idx` (`fk_fecha` ASC),
  INDEX `fk_frecuencias_dim_ruta_estacion1_idx` (`fk_ruta_estacion` ASC),
  INDEX `fk_frecuencias_dim_tiempo1_idx` (`fk_tiempo` ASC),
  CONSTRAINT `fk_frecuencias_dim_fecha`
    FOREIGN KEY (`fk_fecha`)
    REFERENCES `ETLMIO`.`dim_fecha` (`id_fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frecuencias_dim_ruta_estacion1`
    FOREIGN KEY (`fk_ruta_estacion`)
    REFERENCES `ETLMIO`.`dim_ruta_estacion` (`id_ruta_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frecuencias_dim_tiempo1`
    FOREIGN KEY (`fk_tiempo`)
    REFERENCES `ETLMIO`.`dim_tiempo` (`id_tiempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabla que almacena los Hechos de Frecuencia de Pasajeros';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
