/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.ControllerGUI;

/**
 *
 * @author sebaxtian
 */
public class GuiSelectEstaciones extends javax.swing.JFrame {

    /**
     * Creates new form GuiSelectEstaciones
     */
    public GuiSelectEstaciones() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        ControllerGUI.visibleGuiEstaciones = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listEstaciones = new javax.swing.JList<>();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estaciones");

        listEstaciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "7 AGOSTO", "A.SANIN", "ALAMOS", "AMANECER", "AMERICAS", "ATANASIO", "BELALCAZAR", "BUITRERA", "CAICEDO", "CALDAS", "CALIPSO", "CANAVERALEJO", "CAPRI", "CENTRO", "CHAPINERO", "CHIMINANGOS", "CIEN.PALOS", "CONQUISTADORES", "ERMITA", "ESTADIO", "FATIMA", "FLORA IND", "FLORESTA", "FRAY DAMIAN", "LIDO", "MANZANARES", "MELENDEZ", "MZ. SABER", "NUEVO LATIR", "PAMPALINDA", "PETECUY", "PILOTO", "PLZ TOROS", "POPULAR", "PRADOS", "PRIMITIVO", "REFUGIO", "RIO CALI", "SALOMIA", "SAN BOSCO", "SAN NICOLA", "SAN PASCUA", "SAN PEDRO", "SANTA ROSA", "ST LIBRADA", "STA.MONICA", "SUCRE", "T. CALI", "TEQUENDAMA", "TERMINAL MENGA", "TR.UNIDA", "TREBOL", "UND DEPORT", "UNIVALLE", "UNIVERSIDA", "V.NUEVA", "VERSALLES", "VILLACOL", "VIPASA" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listEstaciones);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        ControllerGUI.setSelectEstaciones(listEstaciones.getSelectedValuesList());
        ControllerGUI.visibleGuiEstaciones = false;
        dispose();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiSelectEstaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiSelectEstaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiSelectEstaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiSelectEstaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiSelectEstaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listEstaciones;
    // End of variables declaration//GEN-END:variables
}
